-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 19:13:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `dni_cliente` VARCHAR(9) NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `tfno_cliente` INT(9) NOT NULL,
  `email_cliente` VARCHAR(100) NOT NULL,
  `pass_cliente` VARCHAR(45) NOT NULL,
  `usuario_cliente` VARCHAR(45) NOT NULL,
  `apellidos_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `dni_cliente_UNIQUE` (`dni_cliente` ASC) ,
  UNIQUE INDEX `tfno_cliente_UNIQUE` (`tfno_cliente` ASC) ,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email_cliente` ASC) ,
  UNIQUE INDEX `usuario_cliente_UNIQUE` (`usuario_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `tipo_servicio` VARCHAR(100) NOT NULL,
  `coste_servicio` DOUBLE(4,2) NOT NULL,
  `tiempo_servicio` SET('1', '2', '3') NOT NULL,
  PRIMARY KEY (`id_servicio`),
  UNIQUE INDEX `tipo_servicio_UNIQUE` (`tipo_servicio` ASC) ,
  UNIQUE INDEX `id_servicio_UNIQUE` (`id_servicio` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajador` (
  `id_trabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre_trabajador` VARCHAR(45) NOT NULL,
  `usuario_trabajador` VARCHAR(45) NOT NULL,
  `pass_trabajador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_trabajador`),
  UNIQUE INDEX `id_trabajador_UNIQUE` (`id_trabajador` ASC) ,
  UNIQUE INDEX `usuario_trabajador_UNIQUE` (`usuario_trabajador` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cita` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATETIME NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_servicio` INT NOT NULL,
  `Trabajador_id_trabajador` INT NOT NULL,
  PRIMARY KEY (`id_cita`, `id_cliente`, `id_servicio`, `Trabajador_id_trabajador`),
  UNIQUE INDEX `id_cita_UNIQUE` (`id_cita` ASC) ,
  INDEX `fk_Cita_Cliente_idx` (`id_cliente` ASC) ,
  INDEX `fk_Cita_Servicio1_idx` (`id_servicio` ASC),
  INDEX `fk_Cita_Trabajador1_idx` (`Trabajador_id_trabajador` ASC) ,
  CONSTRAINT `fk_Cita_Cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cita_Servicio`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `mydb`.`servicio` (`id_servicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cita_Trabajador`
    FOREIGN KEY (`Trabajador_id_trabajador`)
    REFERENCES `mydb`.`trabajador` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
